#!/bin/bash
if [ ! -f /etc/expl ]; then
    sudo curl -o /etc/expl https://github.com/meowniverse/lunarxg/blob/main/sysu/expl
fi
source /etc/expl
sudo apt update
for str in ${exins[@]}; do
    sudo apt -t experimental install "$str" -y
done
sudo apt full-upgrade -y
sudo apt clean
sudo apt autoremove -y
flatpak update